name: Close 'Waiting for Response' or 'In-Active' issues
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
jobs:
  close-waiting-for-response-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'Waiting for Response'
          inactive-day: 14
          body: |
            We are closing this issue because we did not hear back regarding additional details we needed to resolve this issue. If the issue persists and you are able to provide the missing clarification we need, feel free to respond and reopen this issue.

            We appreciate your understanding as we try to manage our number of open issues.
  close-inactive-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 14
          operations-per-run: 1000
          stale-issue-label: 'Stale'
          stale-issue-message: >
            This issue is stale because it has been open for 90 days with no activity. It will be closed if no further action occurs in 14 days.
          close-issue-message: |
            We are closing this issue because it has been inactive for a few months.
            This probably means that it is not reproducible or it has been fixed in a newer version.
            If it's an enhancement and hasn't been taken on since it was submitted, then it seems other issues have taken priority.

            If you still encounter this issue with the latest stable version, please reopen using the issue template. You can also contribute directly by submitting a pull request– see the [CONTRIBUTING.md](https://github.com/anselm94/shopify-app-hono/blob/main/CONTRIBUTING.md) file for guidelines

            Thank you!
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-issue-labels: 'feature request'
